#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

;start suspended 

Suspend

;define and set icons

Icon_Active = D:\Auto Hot Key\ahk-personal\ico\uwu-active.ico
Icon_Suspended = D:\Auto Hot Key\ahk-personal\ico\uwu-suspended.ico

IfExist, %Icon_Suspended%
  Menu, Tray, Icon, %Icon_Suspended%
return


;control suspension and change icon

^!o::
Suspend
IF A_ISSUSPENDED = 1
Menu, tray, icon, %Icon_Suspended%, , 1
else if A_ISSUSPENDED = 0
Menu, tray, icon, %Icon_Active%, , 1
return

;common phrases

::watdis::OwO What's This?
::glhf::good wuck have fwun evewyone :3
::diff::diff :3
::fucky::OOPSIE WOOPSIE!! Uwu We make a fucky wucky!! A wittle fucko boingo!

;copy pastas

::pastarawr::RAWR x3 *nuzzlez* pounces on u uwu u so warm. couldn't help but notice ur bulge from across the floor. nuzzlez yo' necky wecky~ murr~ hehe. unzips yo baggy ass pants oof baby u so musky. take me home, pet me, N' make me yours & dont forget to stuff me. see me wag my widdle baby tail, all for your bolgy-wolgy. kisses n lickies yo neck, i hope daddy likeies. nuzzles n wuzzles yo chest, i be gettin thirsty. hey i got a lil itch u think u can help me? only seven inches long UwU PLS ADOPT ME. paws on ur bulge as i lick my lips uwu punish me pls. bout to hit'em with this furry shit. you dont see it coming pounces on you u ded'd
::pastapowice::UwU This is the LA Powice Depawtment, we awe fowwowing up on a sewies of weports of that youw huge bolgy wolgy has been distuwbing the peace in the neighbowhood, so we will be taking you and youw bolgy wolgy OwO into ouw custody, and it is pawt of the pwoceduwe fow us to nuzzle and wuzzle youw necky wecky ~ murr~ hehe UwU
::pastagod::God is dead. God wemains dead. And we have kiwwed him.
::pastagodfull::God is dead. God wemains dead. And we have kiwwed him. How shaww we comfowt ouwsewves, the mwuwdewews of aww mwuwdewews?? what was howiest and mwightiest of aww that the wowwd has yet owned has bwed to death undew ouw knives: who wiww wipe this bwood off us?? what watew is thewe fow us to cwean ouwsewves?? what festivaws of atonement, what sacwed games shaww we have to invent?? is not the gweatness of this deed too gweat fow us?? mwust we ouwsewves not become gods simpwy to appeaw wowthy of it? UwU 

;special characters



;most common words in the English language

::a::a
::abandon::abwandon
::ability::abiwity
::able::abwe
::abortion::abowtion
::about::abouwt
::above::above
::abroad::abwoad
::absence::absence
::absolute::absowute
::absolutely::absowutewy
::absorb::absowb
::abuse::abuse
::a::academic
::accept::accept
::access::access
::accident::accident
::accompany::accompany
::accomplish::accompwish
::according::accowding
::account::account
::accurate::accuwate
::accuse::accuse
::achieve::achieve
::achievement::achievement
::acid::acid
::acknowledge::acknowwedge
::acquire::acquiwe
::across::acwoss
::act::act
::action::action
::active::active
::activist::activist
::activity::activity
::actor::actow
::actress::actwess
::actual::actuaw
::actually::actuawwy
::ad::ad
::adapt::adapt
::add::add
::addition::addition
::additional::additionaw
::address::addwess
::adequate::adequate
::adjust::adjust
::adjustment::adjustment
::administration::administwation
::administrator::administwatow
::admire::admiwe
::admission::admission
::admit::admit
::adolescent::adowescent
::adopt::adopt
::adult::aduwt
::advance::advance
::advanced::advanced
::advantage::advantage
::adventure::adventuwe
::advertising::advewtising
::advice::advice
::advise::advise
::adviser::advisew
::advocate::advocate
::affair::affaiw
::affect::affect
::afford::affowd
::afraid::afwaid
::African::afwican
::African-American::afwican-amewican
::after::aftew
::afternoon::aftewnoon
::again::again
::against::against
::age::age
::agency::agency
::agenda::agenda
::agent::agent
::aggressive::aggwessive
::ago::ago
::agree::agwee
::agreement::agweement
::agricultural::agwicuwtuwaw
::ah::ah
::ahead::ahead
::aid::aid
::aide::aide
::AIDS::aids
::aim::aim
::air::aiw
::aircraft::aiwcwaft
::airline::aiwwine
::airport::aiwpowt
::album::awbum
::alcohol::awcohow
::alive::awive
::all::aww
::alliance::awwiance
::allow::awwow
::ally::awwy
::almost::awmost
::alone::awone
::along::awong
::already::awweady
::also::awso
::alter::awtew
::alternative::awtewnative
::although::awthough
::always::awways
::AM::am
::amazing::amazing
::American::amewican
::among::among
::amount::amount
::analysis::anawysis
::analyst::anawyst
::analyze::anawyze
::ancient::ancient
::and::awnd
::anger::angew
::angle::angwe
::angry::angwy
::animal::animaw
::anniversary::annivewsawy
::announce::announce
::annual::annuaw
::another::anothew
::answer::answew
::anticipate::anticipate
::anxiety::anxiety
::any::any
::anybody::anybody
::anymore::anymowe
::anyone::anyone
::anything::anything
::anyway::anyway
::anywhere::anywhewe
::apart::apawt
::apartment::apawtment
::apparent::appawent
::apparently::appawentwy
::appeal::appeaw
::appear::appeaw
::appearance::appeawance
::apple::appwe
::application::appwication
::apply::appwy
::appoint::appoint
::appointment::appointment
::appreciate::appweciate
::approach::appwoach
::appropriate::appwopwiate
::approval::appwovaw
::approve::appwove
::approximately::appwoximatewy
::Arab::awab
::architect::awchitect
::area::awea
::argue::awgue
::argument::awgument
::arise::awise
::arm::awm
::armed::awmed
::army::awmy
::around::awound
::arrange::awwange
::arrangement::awwangement
::arrest::awwest
::arrival::awwivaw
::arrive::awwive
::art::awt
::article::awticwe
::artist::awtist
::artistic::awtistic
::as::as
::Asian::asian
::aside::aside
::ask::awsk
::asleep::asweep
::aspect::aspect
::assault::assauwt
::assert::assewt
::assess::assess
::assessment::assessment
::asset::asset
::assign::assign
::assignment::assignment
::assist::assist
::assistance::assistance
::assistant::assistant
::associate::associate
::association::association
::assume::assume
::assumption::assumption
::assure::assuwe
::at::at
::athlete::athwete
::athletic::athwetic
::atmosphere::atmosphewe
::attach::attach
::attack::attack
::attempt::attempt
::attend::attend
::attention::attention
::attitude::attitude
::attorney::attowney
::attract::attwact
::attractive::attwactive
::attribute::attwibute
::audience::audience
::author::authow
::authority::authowity
::auto::auto
::available::avaiwabwe
::average::avewage
::avoid::avoid
::award::awawd
::aware::awawe
::awareness::awaweness
::away::away
::awful::awfuw
::baby::baby
::back::bawck
::background::backgwound
::bad::bad
::badly::badwy
::bag::bag
::bake::bake
::balance::bawance
::ball::baww
::ban::ban
::band::band
::bank::bank
::bar::baw
::barely::bawewy
::barrel::bawwew
::barrier::bawwiew
::base::base
::baseball::basebaww
::basic::basic
::basically::basicawwy
::basis::basis
::basket::basket
::basketball::basketbaww
::bathroom::bathwoom
::battery::battewy
::battle::battwe
::be::be
::beach::beach
::bean::bean
::bear::beaw
::beat::beat
::beautiful::beautifuw
::beauty::beauty
::because::because
::become::become
::bed::bed
::bedroom::bedwoom
::beer::beew
::before::befowe
::begin::begin
::beginning::beginning
::behavior::behaviow
::behind::behind
::being::being
::belief::bewief
::believe::bewieve
::bell::beww
::belong::bewong
::below::bewow
::belt::bewt
::bench::bench
::bend::bend
::beneath::beneath
::benefit::benefit
::beside::beside
::besides::besides
::best::best
::bet::bet
::better::bettew
::between::between
::beyond::beyond
::Bible::bibwe
::big::big
::bike::bike
::bill::biww
::billion::biwwion
::bind::bind
::biological::biowogicaw
::bird::biwd
::birth::biwth
::birthday::biwthday
::bit::bit
::bite::bite
::black::bwack
::blade::bwade
::blame::bwame
::blanket::bwanket
::blind::bwind
::block::bwock
::blood::bwood
::blow::bwow
::blue::bwue
::board::boawd
::boat::boat
::body::body
::bomb::bomb
::bombing::bombing
::bond::bond
::bone::bone
::book::book
::boom::boom
::boot::boot
::border::bowdew
::born::bown
::borrow::bowwow
::boss::boss
::both::both
::bother::bothew
::bottle::bottwe
::bottom::bottom
::boundary::boundawy
::bowl::boww
::box::box
::boy::boy
::boyfriend::boyfwiend
::brain::bwain
::branch::bwanch
::brand::bwand
::bread::bwead
::break::bweak
::breakfast::bweakfast
::breast::bweast
::breath::bweath
::breathe::bweathe
::brick::bwick
::bridge::bwidge
::brief::bwief
::briefly::bwiefwy
::bright::bwight
::brilliant::bwiwwiant
::bring::bwing
::British::bwitish
::broad::bwoad
::broken::bwoken
::brother::bwothew
::brown::bwown
::brush::bwush
::buck::buck
::budget::budget
::build::buiwd
::building::buiwding
::bullet::buwwet
::bunch::bunch
::burden::buwden
::burn::buwn
::bury::buwy
::bus::bus
::business::business
::busy::busy
::but::but
::butter::buttew
::button::button
::buy::buy
::buyer::buyew
::by::by
::cabin::cabin
::cabinet::cabinet
::cable::cabwe
::cake::cake
::calculate::cawcuwate
::call::caww
::camera::camewa
::camp::camp
::campaign::campaign
::campus::campus
::can::cawn
::Canadian::canadian
::cancer::cancew
::candidate::candidate
::cap::cap
::capability::capabiwity
::capable::capabwe
::capacity::capacity
::capital::capitaw
::captain::captain
::capture::captuwe
::car::caw
::carbon::cawbon
::card::cawd
::care::cawe
::career::caweew
::careful::cawefuw
::carefully::cawefuwwy
::carrier::cawwiew
::carry::cawwy
::case::case
::cash::cash
::cast::cast
::catch::catch
::category::categowy
::Catholic::cathowic
::cause::cause
::ceiling::ceiwing
::celebrate::cewebwate
::celebration::cewebwation
::celebrity::cewebwity
::cell::ceww
::center::centew
::central::centwaw
::century::centuwy
::CEO::ceo
::ceremony::cewemony
::certain::cewtain
::certainly::cewtainwy
::chain::chain
::chair::chaiw
::chairman::chaiwman
::challenge::chawwenge
::chamber::chambew
::champion::champion
::championship::championship
::chance::chance
::change::change
::changing::changing
::channel::channew
::chapter::chaptew
::character::chawactew
::characteristic::chawactewistic
::characterize::chawactewize
::charge::chawge
::charity::chawity
::chart::chawt
::chase::chase
::cheap::cheap
::check::check
::cheek::cheek
::cheese::cheese
::chef::chef
::chemical::chemicaw
::chest::chest
::chicken::chicken
::chief::chief
::child::chiwd
::childhood::chiwdhood
::Chinese::chinese
::chip::chip
::chocolate::chocowate
::choice::choice
::cholesterol::chowestewow
::choose::choose
::Christian::chwistian
::Christmas::chwistmas
::church::chuwch
::cigarette::cigawette
::circle::ciwcwe
::circumstance::ciwcumstance
::cite::cite
::citizen::citizen
::city::city
::civil::civiw
::civilian::civiwian
::claim::cwaim
::class::cwass
::classic::cwassic
::classroom::cwasswoom
::clean::cwean
::clear::cweaw
::clearly::cweawwy
::client::cwient
::climate::cwimate
::climb::cwimb
::clinic::cwinic
::clinical::cwinicaw
::clock::cwock
::close::cwose
::closely::cwosewy
::closer::cwosew
::clothes::cwothes
::clothing::cwothing
::cloud::cwoud
::club::cwub
::clue::cwue
::cluster::cwustew
::coach::coach
::coal::coaw
::coalition::coawition
::coast::coast
::coat::coat
::code::code
::coffee::coffee
::cognitive::cognitive
::cold::cowd
::collapse::cowwapse
::colleague::cowweague
::collect::cowwect
::collection::cowwection
::collective::cowwective
::college::cowwege
::colonial::cowoniaw
::color::cowow
::column::cowumn
::combination::combination
::combine::combine
::come::come
::comedy::comedy
::comfort::comfowt
::comfortable::comfowtabwe
::command::command
::commander::commandew
::comment::comment
::commercial::commewciaw
::commission::commission
::commit::commit
::commitment::commitment
::committee::committee
::common::common
::communicate::communicate
::communication::communication
::community::community
::company::company
::compare::compawe
::comparison::compawison
::compete::compete
::competition::competition
::competitive::competitive
::competitor::competitow
::complain::compwain
::complaint::compwaint
::complete::compwete
::completely::compwetewy
::complex::compwex
::complicated::compwicated
::component::component
::compose::compose
::composition::composition
::comprehensive::compwehensive
::computer::computew
::concentrate::concentwate
::concentration::concentwation
::concept::concept
::concern::concewn
::concerned::concewned
::concert::concewt
::conclude::concwude
::conclusion::concwusion
::concrete::concwete
::condition::condition
::conduct::conduct
::conference::confewence
::confidence::confidence
::confident::confident
::confirm::confiwm
::conflict::confwict
::confront::confwont
::confusion::confusion
::Congress::congwess
::congressional::congwessionaw
::connect::connect
::connection::connection
::consciousness::consciousness
::consensus::consensus
::consequence::consequence
::conservative::consewvative
::consider::considew
::considerable::considewabwe
::consideration::considewation
::consist::consist
::consistent::consistent
::constant::constant
::constantly::constantwy
::constitute::constitute
::constitutional::constitutionaw
::construct::constwuct
::construction::constwuction
::consultant::consuwtant
::consume::consume
::consumer::consumew
::consumption::consumption
::contact::contact
::contain::contain
::container::containew
::contemporary::contempowawy
::content::content
::contest::contest
::context::context
::continue::continue
::continued::continued
::contract::contwact
::contrast::contwast
::contribute::contwibute
::contribution::contwibution
::control::contwow
::controversial::contwovewsiaw
::controversy::contwovewsy
::convention::convention
::conventional::conventionaw
::conversation::convewsation
::convert::convewt
::conviction::conviction
::convince::convince
::cook::cook
::cookie::cookie
::cooking::cooking
::cool::coow
::cooperation::coopewation
::cop::cop
::cope::cope
::copy::copy
::core::cowe
::corn::cown
::corner::cownew
::corporate::cowpowate
::corporation::cowpowation
::correct::cowwect
::correspondent::cowwespondent
::cost::cost
::cotton::cotton
::couch::couch
::could::couwd
::council::counciw
::counselor::counsewow
::count::count
::counter::countew
::country::countwy
::county::county
::couple::coupwe
::courage::couwage
::course::couwse
::court::couwt
::cousin::cousin
::cover::covew
::coverage::covewage
::cow::cow
::crack::cwack
::craft::cwaft
::crash::cwash
::crazy::cwazy
::cream::cweam
::create::cweate
::creation::cweation
::creative::cweative
::creature::cweatuwe
::credit::cwedit
::crew::cwew
::crime::cwime
::criminal::cwiminaw
::crisis::cwisis
::criteria::cwitewia
::critic::cwitic
::critical::cwiticaw
::criticism::cwiticism
::criticize::cwiticize
::crop::cwop
::cross::cwoss
::crowd::cwowd
::crucial::cwuciaw
::cry::cwy
::cultural::cuwtuwaw
::culture::cuwtuwe
::cup::cup
::curious::cuwious
::current::cuwwent
::currently::cuwwentwy
::curriculum::cuwwicuwum
::custom::custom
::customer::customew
::cut::cut
::cycle::cycwe
::dad::dad
::daily::daiwy
::damage::damage
::dance::dance
::danger::dangew
::dangerous::dangewous
::dare::dawe
::dark::dawk
::darkness::dawkness
::data::data
::date::date
::daughter::daughtew
::day::day
::dead::dead
::deal::deaw
::dealer::deawew
::dear::deaw
::death::death
::debate::debate
::debt::debt
::decade::decade
::decide::decide
::decision::decision
::deck::deck
::declare::decwawe
::decline::decwine
::decrease::decwease
::deep::deep
::deeply::deepwy
::deer::deew
::defeat::defeat
::defend::defend
::defendant::defendant
::defense::defense
::defensive::defensive
::deficit::deficit
::define::define
::definitely::definitewy
::definition::definition
::degree::degwee
::delay::deway
::deliver::dewivew
::delivery::dewivewy
::demand::demand
::democracy::democwacy
::Democrat::democwat
::democratic::democwatic
::demonstrate::demonstwate
::demonstration::demonstwation
::deny::deny
::department::depawtment
::depend::depend
::dependent::dependent
::depending::depending
::depict::depict
::depression::depwession
::depth::depth
::deputy::deputy
::derive::dewive
::describe::descwibe
::description::descwiption
::desert::desewt
::deserve::desewve
::design::design
::designer::designew
::desire::desiwe
::desk::desk
::desperate::despewate
::despite::despite
::destroy::destwoy
::destruction::destwuction
::detail::detaiw
::detailed::detaiwed
::detect::detect
::determine::detewmine
::develop::devewop
::developing::devewoping
::development::devewopment
::device::device
::devote::devote
::dialogue::diawogue
::die::die
::diet::diet
::differ::diffew
::difference::diffewence
::different::diffewent
::differently::diffewentwy
::difficult::difficuwt
::difficulty::difficuwty
::dig::dig
::digital::digitaw
::dimension::dimension
::dining::dining
::dinner::dinnew
::direct::diwect
::direction::diwection
::directly::diwectwy
::director::diwectow
::dirt::diwt
::dirty::diwty
::disability::disabiwity
::disagree::disagwee
::disappear::disappeaw
::disaster::disastew
::discipline::discipwine
::discourse::discouwse
::discover::discovew
::discovery::discovewy
::discrimination::discwimination
::discuss::discuss
::discussion::discussion
::disease::disease
::dish::dish
::dismiss::dismiss
::disorder::disowdew
::display::dispway
::dispute::dispute
::distance::distance
::distant::distant
::distinct::distinct
::distinction::distinction
::distinguish::distinguish
::distribute::distwibute
::distribution::distwibution
::district::distwict
::diverse::divewse
::diversity::divewsity
::divide::divide
::division::division
::divorce::divowce
::DNA::dna
::do::duwu
::doctor::doctow
::document::document
::domestic::domestic
::dominant::dominant
::dominate::dominate
::door::doow
::double::doubwe
::doubt::doubt
::down::down
::downtown::downtown
::dozen::dozen
::draft::dwaft
::drag::dwag
::drama::dwama
::dramatic::dwamatic
::dramatically::dwamaticawwy
::draw::dwaw
::drawing::dwawing
::dream::dweam
::dress::dwess
::drink::dwink
::drive::dwive
::driver::dwivew
::drop::dwop
::drug::dwug
::dry::dwy
::due::due
::during::duwing
::dust::dust
::duty::duty
::each::each
::eager::eagew
::ear::eaw
::early::eawwy
::earn::eawn
::earnings::eawnings
::earth::eawth
::ease::ease
::easily::easiwy
::east::east
::eastern::eastewn
::easy::easy
::eat::eat
::economic::economic
::economics::economics
::economist::economist
::economy::economy
::edge::edge
::edition::edition
::editor::editow
::educate::educate
::education::education
::educational::educationaw
::educator::educatow
::effect::effect
::effective::effective
::effectively::effectivewy
::efficiency::efficiency
::efficient::efficient
::effort::effowt
::egg::egg
::eight::eight
::either::eithew
::elderly::ewdewwy
::elect::ewect
::election::ewection
::electric::ewectwic
::electricity::ewectwicity
::electronic::ewectwonic
::element::ewement
::elementary::ewementawy
::eliminate::ewiminate
::elite::ewite
::else::ewse
::elsewhere::ewsewhewe
::e-mail::e-maiw
::embrace::embwace
::emerge::emewge
::emergency::emewgency
::emission::emission
::emotion::emotion
::emotional::emotionaw
::emphasis::emphasis
::emphasize::emphasize
::employ::empwoy
::employee::empwoyee
::employer::empwoyew
::employment::empwoyment
::empty::empty
::enable::enabwe
::encounter::encountew
::encourage::encouwage
::end::end
::enemy::enemy
::energy::enewgy
::enforcement::enfowcement
::engage::engage
::engine::engine
::engineer::engineew
::engineering::engineewing
::English::engwish
::enhance::enhance
::enjoy::enjoy
::enormous::enowmous
::enough::enough
::ensure::ensuwe
::enter::entew
::enterprise::entewpwise
::entertainment::entewtainment
::entire::entiwe
::entirely::entiwewy
::entrance::entwance
::entry::entwy
::environment::enviwonment
::environmental::enviwonmentaw
::episode::episode
::equal::equaw
::equally::equawwy
::equipment::equipment
::era::ewa
::error::ewwow
::escape::escape
::especially::especiawwy
::essay::essay
::essential::essentiaw
::essentially::essentiawwy
::establish::estabwish
::establishment::estabwishment
::estate::estate
::estimate::estimate
::etc::etc
::ethics::ethics
::ethnic::ethnic
::European::euwopean
::evaluate::evawuate
::evaluation::evawuation
::even::even
::evening::evening
::event::event
::eventually::eventuawwy
::ever::evew
::every::evewy
::everybody::evewybody
::everyday::evewyday
::everyone::evewyone
::everything::evewything
::everywhere::evewywhewe
::evidence::evidence
::evolution::evowution
::evolve::evowve
::exact::exact
::exactly::exactwy
::examination::examination
::examine::examine
::example::exampwe
::exceed::exceed
::excellent::excewwent
::except::except
::exception::exception
::exchange::exchange
::exciting::exciting
::executive::executive
::exercise::exewcise
::exhibit::exhibit
::exhibition::exhibition
::exist::exist
::existence::existence
::existing::existing
::expand::expand
::expansion::expansion
::expect::expect
::expectation::expectation
::expense::expense
::expensive::expensive
::experience::expewience
::experiment::expewiment
::expert::expewt
::explain::expwain
::explanation::expwanation
::explode::expwode
::explore::expwowe
::explosion::expwosion
::expose::expose
::exposure::exposuwe
::express::expwess
::expression::expwession
::extend::extend
::extension::extension
::extensive::extensive
::extent::extent
::external::extewnaw
::extra::extwa
::extraordinary::extwaowdinawy
::extreme::extweme
::extremely::extwemewy
::eye::eye
::fabric::fabwic
::face::face
::facility::faciwity
::fact::fact
::factor::factow
::factory::factowy
::faculty::facuwty
::fade::fade
::fail::faiw
::failure::faiwuwe
::fair::faiw
::fairly::faiwwy
::faith::faith
::fall::faww
::FALSE::fawse
::familiar::famiwiaw
::family::famiwy
::famous::famous
::fan::fan
::fantasy::fantasy
::far::faw
::farm::fawm
::farmer::fawmew
::fashion::fashion
::fast::fawst
::fat::fat
::fate::fate
::father::fathew
::fault::fauwt
::favor::favow
::favorite::favowite
::fear::feaw
::feature::featuwe
::federal::fedewaw
::fee::fee
::feed::feed
::feel::feew
::feeling::feewing
::fellow::fewwow
::female::femawe
::fence::fence
::few::few
::fewer::fewew
::fiber::fibew
::fiction::fiction
::field::fiewd
::fifteen::fifteen
::fifth::fifth
::fifty::fifty
::fight::fight
::fighter::fightew
::fighting::fighting
::figure::figuwe
::file::fiwe
::fill::fiww
::film::fiwm
::final::finaw
::finally::finawwy
::finance::finance
::financial::financiaw
::find::find
::finding::finding
::fine::fine
::finger::fingew
::finish::finish
::fire::fiwe
::firm::fiwm
::first::fiwst
::fish::fish
::fishing::fishing
::fit::fit
::fitness::fitness
::five::five
::fix::fix
::flag::fwag
::flame::fwame
::flat::fwat
::flavor::fwavow
::flee::fwee
::flesh::fwesh
::flight::fwight
::float::fwoat
::floor::fwoow
::flow::fwow
::flower::fwowew
::fly::fwy
::focus::focus
::folk::fowk
::follow::fowwow
::following::fowwowing
::food::food
::foot::foot
::football::footbaww
::for::fow
::force::fowce
::foreign::foweign
::forest::fowest
::forever::fowevew
::forget::fowget
::form::fowm
::formal::fowmaw
::formation::fowmation
::former::fowmew
::formula::fowmuwa
::forth::fowth
::fortune::fowtune
::forward::fowwawd
::found::found
::foundation::foundation
::founder::foundew
::four::fouw
::fourth::fouwth
::frame::fwame
::framework::fwamewowk
::free::fwee
::freedom::fweedom
::freeze::fweeze
::French::fwench
::frequency::fwequency
::frequent::fwequent
::frequently::fwequentwy
::fresh::fwesh
::friend::fwiend
::friendly::fwiendwy
::friendship::fwiendship
::from::fwom
::front::fwont
::fruit::fwuit
::frustration::fwustwation
::fuel::fuew
::full::fuww
::fully::fuwwy
::fun::fun
::function::function
::fund::fund
::fundamental::fundamentaw
::funding::funding
::funeral::funewaw
::funny::funny
::furniture::fuwnituwe
::furthermore::fuwthewmowe
::future::futuwe
::gain::gain
::galaxy::gawaxy
::gallery::gawwewy
::game::gawme
::gang::gang
::gap::gap
::garage::gawage
::garden::gawden
::garlic::gawwic
::gas::gas
::gate::gate
::gather::gathew
::gay::gay
::gaze::gaze
::gear::geaw
::gender::gendew
::gene::gene
::general::genewaw
::generally::genewawwy
::generate::genewate
::generation::genewation
::genetic::genetic
::gentleman::gentweman
::gently::gentwy
::German::gewman
::gesture::gestuwe
::get::get
::ghost::ghost
::giant::giant
::gift::gift
::gifted::gifted
::girl::giww
::girlfriend::giwwfwiend
::give::give
::given::given
::glad::gwad
::glance::gwance
::glass::gwass
::global::gwobaw
::glove::gwove
::go::gow
::goal::goaw
::God::god
::gold::gowd
::golden::gowden
::golf::gowf
::good::good
::government::govewnment
::governor::govewnow
::grab::gwab
::grade::gwade
::gradually::gwaduawwy
::graduate::gwaduate
::grain::gwain
::grand::gwand
::grandfather::gwandfathew
::grandmother::gwandmothew
::grant::gwant
::grass::gwass
::grave::gwave
::gray::gway
::great::gweat
::greatest::gweatest
::green::gween
::grocery::gwocewy
::ground::gwound
::group::gwoup
::grow::gwow
::growing::gwowing
::growth::gwowth
::guarantee::guawantee
::guard::guawd
::guess::guess
::guest::guest
::guide::guide
::guideline::guidewine
::guilty::guiwty
::gun::gun
::guy::guy
::habit::habit
::habitat::habitat
::hair::haiw
::half::hawf
::hall::haww
::hand::hawnd
::handful::handfuw
::handle::handwe
::hang::hang
::happen::happen
::happy::happy
::hard::hawd
::hardly::hawdwy
::hat::hat
::hate::hate
::have::have
::he::he
::head::head
::headline::headwine
::headquarters::headquawtews
::health::heawth
::healthy::heawthy
::hear::heaw
::hearing::heawing
::heart::heawt
::heat::heat
::heaven::heaven
::heavily::heaviwy
::heavy::heavy
::heel::heew
::height::height
::helicopter::hewicoptew
::hell::heww
::hello::hewwo
::help::hewp
::helpful::hewpfuw
::her::hew
::here::hewe
::heritage::hewitage
::hero::hewo
::herself::hewsewf
::hi::hi
::hide::hide
::high::high
::highlight::highwight
::highly::highwy
::highway::highway
::hill::hiww
::him::him
::himself::himsewf
::hip::hip
::hire::hiwe
::his::hiws
::historian::histowian
::historic::histowic
::historical::histowicaw
::history::histowy
::hit::hit
::hold::howd
::hole::howe
::holiday::howiday
::holy::howy
::home::home
::homeless::homewess
::honest::honest
::honey::honey
::honor::honow
::hope::hope
::horizon::howizon
::horror::howwow
::horse::howse
::hospital::hospitaw
::host::host
::hot::hot
::hotel::hotew
::hour::houw
::house::house
::household::househowd
::housing::housing
::how::how
::however::howevew
::huge::huge
::human::human
::humor::humow
::hundred::hundwed
::hungry::hungwy
::hunter::huntew
::hunting::hunting
::hurt::huwt
::husband::husband
::hypothesis::hypothesis
::I::i
::ice::ice
::idea::idea
::ideal::ideaw
::identification::identification
::identify::identify
::identity::identity
::ie::ie
::if::if
::ignore::ignowe
::ill::iww
::illegal::iwwegaw
::illness::iwwness
::illustrate::iwwustwate
::image::image
::imagination::imagination
::imagine::imagine
::immediate::immediate
::immediately::immediatewy
::immigrant::immigwant
::immigration::immigwation
::impact::impact
::implement::impwement
::implication::impwication
::imply::impwy
::importance::impowtance
::important::impowtant
::impose::impose
::impossible::impossibwe
::impress::impwess
::impression::impwession
::impressive::impwessive
::improve::impwove
::improvement::impwovement
::in::in
::incentive::incentive
::incident::incident
::include::incwude
::including::incwuding
::income::income
::incorporate::incowpowate
::increase::incwease
::increased::incweased
::increasing::incweasing
::increasingly::incweasingwy
::incredible::incwedibwe
::indeed::indeed
::independence::independence
::independent::independent
::index::index
::Indian::indian
::indicate::indicate
::indication::indication
::individual::individuaw
::industrial::industwiaw
::industry::industwy
::infant::infant
::infection::infection
::inflation::infwation
::influence::infwuence
::inform::infowm
::information::infowmation
::ingredient::ingwedient
::initial::initiaw
::initially::initiawwy
::initiative::initiative
::injury::injuwy
::inner::innew
::innocent::innocent
::inquiry::inquiwy
::inside::inside
::insight::insight
::insist::insist
::inspire::inspiwe
::install::instaww
::instance::instance
::instead::instead
::institution::institution
::institutional::institutionaw
::instruction::instwuction
::instructor::instwuctow
::instrument::instwument
::insurance::insuwance
::intellectual::intewwectuaw
::intelligence::intewwigence
::intend::intend
::intense::intense
::intensity::intensity
::intention::intention
::interaction::intewaction
::interest::intewest
::interested::intewested
::interesting::intewesting
::internal::intewnaw
::international::intewnationaw
::Internet::intewnet
::interpret::intewpwet
::interpretation::intewpwetation
::intervention::intewvention
::interview::intewview
::into::intwo
::introduce::intwoduce
::introduction::intwoduction
::invasion::invasion
::invest::invest
::investigate::investigate
::investigation::investigation
::investigator::investigatow
::investment::investment
::investor::investow
::invite::invite
::involve::invowve
::involved::invowved
::involvement::invowvement
::Iraqi::iwaqi
::Irish::iwish
::iron::iwon
::Islamic::iswamic
::island::iswand
::Israeli::iswaewi
::issue::issue
::it::iwt
::Italian::itawian
::item::item
::its::its
::itself::itsewf
::jacket::jacket
::jail::jaiw
::Japanese::japanese
::jet::jet
::Jew::jew
::Jewish::jewish
::job::job
::join::join
::joint::joint
::joke::joke
::journal::jouwnaw
::journalist::jouwnawist
::journey::jouwney
::joy::joy
::judge::judge
::judgment::judgment
::juice::juice
::jump::jump
::junior::juniow
::jury::juwy
::just::juwst
::justice::justice
::justify::justify
::keep::keep
::key::key
::kick::kick
::kid::kid
::kill::kiww
::killer::kiwwew
::killing::kiwwing
::kind::kind
::king::king
::kiss::kiss
::kitchen::kitchen
::knee::knee
::knife::knife
::knock::knock
::know::know
::knowledge::knowwedge
::lab::wab
::label::wabew
::labor::wabow
::laboratory::wabowatowy
::lack::wack
::lady::wady
::lake::wake
::land::wand
::landscape::wandscape
::language::wanguage
::lap::wap
::large::wawge
::largely::wawgewy
::last::wast
::late::wate
::later::watew
::Latin::watin
::latter::wattew
::laugh::waugh
::launch::waunch
::law::waw
::lawn::wawn
::lawsuit::wawsuit
::lawyer::wawyew
::lay::way
::layer::wayew
::lead::wead
::leader::weadew
::leadership::weadewship
::leading::weading
::leaf::weaf
::league::weague
::lean::wean
::learn::weawn
::learning::weawning
::least::weast
::leather::weathew
::leave::weave
::left::weft
::leg::weg
::legacy::wegacy
::legal::wegaw
::legend::wegend
::legislation::wegiswation
::legitimate::wegitimate
::lemon::wemon
::length::wength
::less::wess
::lesson::wesson
::let::wet
::letter::wettew
::level::wevew
::liberal::wibewaw
::library::wibwawy
::license::wicense
::lie::wie
::life::wife
::lifestyle::wifestywe
::lifetime::wifetime
::lift::wift
::light::wight
::like::wike
::likely::wikewy
::limit::wimit
::limitation::wimitation
::limited::wimited
::line::wine
::link::wink
::lip::wip
::list::wist
::listen::wisten
::literally::witewawwy
::literary::witewawy
::literature::witewatuwe
::little::wittwe
::live::wive
::living::wiving
::load::woad
::loan::woan
::local::wocaw
::locate::wocate
::location::wocation
::lock::wock
::long::wong
::long-term::wong-tewm
::look::wook
::loose::woose
::lose::wose
::loss::woss
::lost::wost
::lot::wot
::lots::wots
::loud::woud
::love::wove
::lovely::wovewy
::lover::wovew
::low::wow
::lower::wowew
::luck::wuck
::lucky::wucky
::lunch::wunch
::lung::wung
::machine::machine
::mad::mad
::magazine::magazine
::mail::maiw
::main::main
::mainly::mainwy
::maintain::maintain
::maintenance::maintenance
::major::majow
::majority::majowity
::make::make
::maker::makew
::makeup::makeup
::male::mawe
::mall::maww
::man::man
::manage::manage
::management::management
::manager::managew
::manner::mannew
::manufacturer::manufactuwew
::manufacturing::manufactuwing
::many::many
::map::map
::margin::mawgin
::mark::mawk
::market::mawket
::marketing::mawketing
::marriage::mawwiage
::married::mawwied
::marry::mawwy
::mask::mask
::mass::mass
::massive::massive
::master::mastew
::match::match
::material::matewiaw
::math::math
::matter::mattew
::may::may
::maybe::maybe
::mayor::mayow
::me::me
::meal::meaw
::mean::mean
::meaning::meaning
::meanwhile::meanwhiwe
::measure::measuwe
::measurement::measuwement
::meat::meat
::mechanism::mechanism
::media::media
::medical::medicaw
::medication::medication
::medicine::medicine
::medium::medium
::meet::meet
::meeting::meeting
::member::membew
::membership::membewship
::memory::memowy
::mental::mentaw
::mention::mention
::menu::menu
::mere::mewe
::merely::mewewy
::mess::mess
::message::message
::metal::metaw
::meter::metew
::method::method
::Mexican::mexican
::middle::middwe
::might::might
::military::miwitawy
::milk::miwk
::million::miwwion
::mind::mind
::mine::mine
::minister::ministew
::minor::minow
::minority::minowity
::minute::minute
::miracle::miwacwe
::mirror::miwwow
::miss::miss
::missile::missiwe
::mission::mission
::mistake::mistake
::mix::mix
::mixture::mixtuwe
::mm-hmm::mm-hmm
::mode::mode
::model::modew
::moderate::modewate
::modern::modewn
::modest::modest
::mom::mom
::moment::moment
::money::money
::monitor::monitow
::month::month
::mood::mood
::moon::moon
::moral::mowaw
::more::mowe
::moreover::moweovew
::morning::mowning
::mortgage::mowtgage
::most::most
::mostly::mostwy
::mother::mothew
::motion::motion
::motivation::motivation
::motor::motow
::mount::mount
::mountain::mountain
::mouse::mouse
::mouth::mouth
::move::move
::movement::movement
::movie::movie
::Mr::mw
::Mrs::mws
::Ms::ms
::much::much
::multiple::muwtipwe
::murder::muwdew
::muscle::muscwe
::museum::museum
::music::music
::musical::musicaw
::musician::musician
::Muslim::muswim
::must::must
::mutual::mutuaw
::my::my
::myself::mysewf
::mystery::mystewy
::myth::myth
::naked::naked
::name::nawme
::narrative::nawwative
::narrow::nawwow
::nation::nation
::national::nationaw
::native::native
::natural::natuwaw
::naturally::natuwawwy
::nature::natuwe
::near::neaw
::nearby::neawby
::nearly::neawwy
::necessarily::necessawiwy
::necessary::necessawy
::neck::neck
::need::need
::negative::negative
::negotiate::negotiate
::negotiation::negotiation
::neighbor::neighbow
::neighborhood::neighbowhood
::neither::neithew
::nerve::newve
::nervous::newvous
::net::net
::network::netwowk
::never::nevew
::nevertheless::nevewthewess
::new::new
::newly::newwy
::news::news
::newspaper::newspapew
::next::next
::nice::nice
::night::night
::nine::nine
::no::no
::nobody::nobody
::nod::nod
::noise::noise
::nomination::nomination
::none::none
::nonetheless::nonethewess
::nor::now
::normal::nowmaw
::normally::nowmawwy
::north::nowth
::northern::nowthewn
::nose::nose
::not::nowt
::note::note
::nothing::nothing
::notice::notice
::notion::notion
::novel::novew
::now::now
::nowhere::nowhewe
::n't::n't
::nuclear::nucweaw
::number::numbew
::numerous::numewous
::nurse::nuwse
::nut::nut
::object::object
::objective::objective
::obligation::obwigation
::observation::obsewvation
::observe::obsewve
::observer::obsewvew
::obtain::obtain
::obvious::obvious
::obviously::obviouswy
::occasion::occasion
::occasionally::occasionawwy
::occupation::occupation
::occupy::occupy
::occur::occuw
::ocean::ocean
::odd::odd
::odds::odds
::of::of
::off::off
::offense::offense
::offensive::offensive
::offer::offew
::office::office
::officer::officew
::official::officiaw
::often::often
::oh::oh
::oil::oiw
::ok::ok
::okay::okay
::old::owd
::Olympic::owympic
::on::own
::once::once
::one::owne
::ongoing::ongoing
::onion::onion
::online::onwine
::only::onwy
::onto::onto
::open::open
::opening::opening
::operate::opewate
::operating::opewating
::operation::opewation
::operator::opewatow
::opinion::opinion
::opponent::opponent
::opportunity::oppowtunity
::oppose::oppose
::opposite::opposite
::opposition::opposition
::option::option
::or::ow
::orange::owange
::order::owdew
::ordinary::owdinawy
::organic::owganic
::organization::owganization
::organize::owganize
::orientation::owientation
::origin::owigin
::original::owiginaw
::originally::owiginawwy
::other::othew
::others::othews
::otherwise::othewwise
::ought::ought
::our::ouw
::ourselves::ouwsewves
::out::out
::outcome::outcome
::outside::outside
::oven::oven
::over::ovew
::overall::ovewaww
::overcome::ovewcome
::overlook::ovewwook
::owe::owe
::own::own
::owner::ownew
::pace::pace
::pack::pack
::package::package
::page::page
::pain::pain
::painful::painfuw
::paint::paint
::painter::paintew
::painting::painting
::pair::paiw
::pale::pawe
::Palestinian::pawestinian
::palm::pawm
::pan::pan
::panel::panew
::pant::pant
::paper::papew
::parent::pawent
::park::pawk
::parking::pawking
::part::pawt
::participant::pawticipant
::participate::pawticipate
::participation::pawticipation
::particular::pawticuwaw
::particularly::pawticuwawwy
::partly::pawtwy
::partner::pawtnew
::partnership::pawtnewship
::party::pawty
::pass::pass
::passage::passage
::passenger::passengew
::passion::passion
::past::past
::patch::patch
::path::path
::patient::patient
::pattern::pattewn
::pause::pause
::pay::pay
::payment::payment
::PC::pc
::peace::peace
::peak::peak
::peer::peew
::penalty::penawty
::people::peopwe
::pepper::peppew
::per::pew
::perceive::pewceive
::percentage::pewcentage
::perception::pewception
::perfect::pewfect
::perfectly::pewfectwy
::perform::pewfowm
::performance::pewfowmance
::perhaps::pewhaps
::period::pewiod
::permanent::pewmanent
::permission::pewmission
::permit::pewmit
::person::pewson
::personal::pewsonaw
::personality::pewsonawity
::personally::pewsonawwy
::personnel::pewsonnew
::perspective::pewspective
::persuade::pewsuade
::pet::pet
::phase::phase
::phenomenon::phenomenon
::philosophy::phiwosophy
::phone::phone
::photo::photo
::photograph::photogwaph
::photographer::photogwaphew
::phrase::phwase
::physical::physicaw
::physically::physicawwy
::physician::physician
::piano::piano
::pick::pick
::picture::pictuwe
::pie::pie
::piece::piece
::pile::piwe
::pilot::piwot
::pine::pine
::pink::pink
::pipe::pipe
::pitch::pitch
::place::pwace
::plan::pwan
::plane::pwane
::planet::pwanet
::planning::pwanning
::plant::pwant
::plastic::pwastic
::plate::pwate
::platform::pwatfowm
::play::pway
::player::pwayew
::please::pwease
::pleasure::pweasuwe
::plenty::pwenty
::plot::pwot
::plus::pwus
::PM::pm
::pocket::pocket
::poem::poem
::poet::poet
::poetry::poetwy
::point::point
::pole::powe
::police::powice
::policy::powicy
::political::powiticaw
::politically::powiticawwy
::politician::powitician
::politics::powitics
::poll::poww
::pollution::powwution
::pool::poow
::poor::poow
::pop::pop
::popular::popuwaw
::population::popuwation
::porch::powch
::port::powt
::portion::powtion
::portrait::powtwait
::portray::powtway
::pose::pose
::position::position
::positive::positive
::possess::possess
::possibility::possibiwity
::possible::possibwe
::possibly::possibwy
::post::post
::pot::pot
::potato::potato
::potential::potentiaw
::potentially::potentiawwy
::pound::pound
::pour::pouw
::poverty::povewty
::powder::powdew
::power::powew
::powerful::powewfuw
::practical::pwacticaw
::practice::pwactice
::pray::pway
::prayer::pwayew
::precisely::pwecisewy
::predict::pwedict
::prefer::pwefew
::preference::pwefewence
::pregnancy::pwegnancy
::pregnant::pwegnant
::preparation::pwepawation
::prepare::pwepawe
::prescription::pwescwiption
::presence::pwesence
::present::pwesent
::presentation::pwesentation
::preserve::pwesewve
::president::pwesident
::presidential::pwesidentiaw
::press::pwess
::pressure::pwessuwe
::pretend::pwetend
::pretty::pwetty
::prevent::pwevent
::previous::pwevious
::previously::pweviouswy
::price::pwice
::pride::pwide
::priest::pwiest
::primarily::pwimawiwy
::primary::pwimawy
::prime::pwime
::principal::pwincipaw
::principle::pwincipwe
::print::pwint
::prior::pwiow
::priority::pwiowity
::prison::pwison
::prisoner::pwisonew
::privacy::pwivacy
::private::pwivate
::probably::pwobabwy
::problem::pwobwem
::procedure::pwoceduwe
::proceed::pwoceed
::process::pwocess
::produce::pwoduce
::producer::pwoducew
::product::pwoduct
::production::pwoduction
::profession::pwofession
::professional::pwofessionaw
::professor::pwofessow
::profile::pwofiwe
::profit::pwofit
::program::pwogwam
::progress::pwogwess
::project::pwoject
::prominent::pwominent
::promise::pwomise
::promote::pwomote
::prompt::pwompt
::proof::pwoof
::proper::pwopew
::properly::pwopewwy
::property::pwopewty
::proportion::pwopowtion
::proposal::pwoposaw
::propose::pwopose
::proposed::pwoposed
::prosecutor::pwosecutow
::prospect::pwospect
::protect::pwotect
::protection::pwotection
::protein::pwotein
::protest::pwotest
::proud::pwoud
::prove::pwove
::provide::pwovide
::provider::pwovidew
::province::pwovince
::provision::pwovision
::psychological::psychowogicaw
::psychologist::psychowogist
::psychology::psychowogy
::public::pubwic
::publication::pubwication
::publicly::pubwicwy
::publish::pubwish
::publisher::pubwishew
::pull::puww
::punishment::punishment
::purchase::puwchase
::pure::puwe
::purpose::puwpose
::pursue::puwsue
::push::push
::put::put
::qualify::quawify
::quality::quawity
::quarter::quawtew
::quarterback::quawtewback
::question::question
::quick::quick
::quickly::quickwy
::quiet::quiet
::quietly::quietwy
::quit::quit
::quite::quite
::quote::quote
::race::wace
::racial::waciaw
::radical::wadicaw
::radio::wadio
::rail::waiw
::rain::wain
::raise::waise
::range::wange
::rank::wank
::rapid::wapid
::rapidly::wapidwy
::rare::wawe
::rarely::wawewy
::rate::wate
::rather::wathew
::rating::wating
::ratio::watio
::raw::waw
::reach::weach
::react::weact
::reaction::weaction
::read::wead
::reader::weadew
::reading::weading
::ready::weady
::real::weaw
::reality::weawity
::realize::weawize
::really::weawwy
::reason::weason
::reasonable::weasonabwe
::recall::wecaww
::receive::weceive
::recent::wecent
::recently::wecentwy
::recipe::wecipe
::recognition::wecognition
::recognize::wecognize
::recommend::wecommend
::recommendation::wecommendation
::record::wecowd
::recording::wecowding
::recover::wecovew
::recovery::wecovewy
::recruit::wecwuit
::red::wed
::reduce::weduce
::reduction::weduction
::refer::wefew
::reference::wefewence
::reflect::wefwect
::reflection::wefwection
::reform::wefowm
::refugee::wefugee
::refuse::wefuse
::regard::wegawd
::regarding::wegawding
::regardless::wegawdwess
::regime::wegime
::region::wegion
::regional::wegionaw
::register::wegistew
::regular::weguwaw
::regularly::weguwawwy
::regulate::weguwate
::regulation::weguwation
::reinforce::weinfowce
::reject::weject
::relate::wewate
::relation::wewation
::relationship::wewationship
::relative::wewative
::relatively::wewativewy
::relax::wewax
::release::wewease
::relevant::wewevant
::relief::wewief
::religion::wewigion
::religious::wewigious
::rely::wewy
::remain::wemain
::remaining::wemaining
::remarkable::wemawkabwe
::remember::wemembew
::remind::wemind
::remote::wemote
::remove::wemove
::repeat::wepeat
::repeatedly::wepeatedwy
::replace::wepwace
::reply::wepwy
::report::wepowt
::reporter::wepowtew
::represent::wepwesent
::representation::wepwesentation
::representative::wepwesentative
::Republican::wepubwican
::reputation::weputation
::request::wequest
::require::wequiwe
::requirement::wequiwement
::research::weseawch
::researcher::weseawchew
::resemble::wesembwe
::reservation::wesewvation
::resident::wesident
::resist::wesist
::resistance::wesistance
::resolution::wesowution
::resolve::wesowve
::resort::wesowt
::resource::wesouwce
::respect::wespect
::respond::wespond
::respondent::wespondent
::response::wesponse
::responsibility::wesponsibiwity
::responsible::wesponsibwe
::rest::west
::restaurant::westauwant
::restore::westowe
::restriction::westwiction
::result::wesuwt
::retain::wetain
::retire::wetiwe
::retirement::wetiwement
::return::wetuwn
::reveal::weveaw
::revenue::wevenue
::review::weview
::revolution::wevowution
::rhythm::whythm
::rice::wice
::rich::wich
::rid::wid
::ride::wide
::rifle::wifwe
::right::wight
::ring::wing
::rise::wise
::risk::wisk
::river::wivew
::road::woad
::rock::wock
::role::wowe
::roll::woww
::romantic::womantic
::roof::woof
::room::woom
::root::woot
::rope::wope
::rose::wose
::rough::wough
::roughly::woughwy
::round::wound
::route::woute
::routine::woutine
::row::wow
::rub::wub
::rule::wuwe
::run::wun
::running::wunning
::rural::wuwaw
::rush::wush
::Russian::wussian
::sacred::sacwed
::sad::sad
::safe::safe
::safety::safety
::sake::sake
::salad::sawad
::salary::sawawy
::sale::sawe
::sales::sawes
::salt::sawt
::same::same
::sample::sampwe
::sanction::sanction
::sand::sand
::satellite::satewwite
::satisfaction::satisfaction
::satisfy::satisfy
::sauce::sauce
::save::save
::saving::saving
::say::say
::scale::scawe
::scandal::scandaw
::scared::scawed
::scenario::scenawio
::scene::scene
::schedule::scheduwe
::scheme::scheme
::scholar::schowaw
::scholarship::schowawship
::school::schoow
::science::science
::scientific::scientific
::scientist::scientist
::scope::scope
::score::scowe
::scream::scweam
::screen::scween
::script::scwipt
::sea::sea
::search::seawch
::season::season
::seat::seat
::second::second
::secret::secwet
::secretary::secwetawy
::section::section
::sector::sectow
::secure::secuwe
::security::secuwity
::see::see
::seed::seed
::seek::seek
::seem::seem
::segment::segment
::seize::seize
::select::sewect
::selection::sewection
::self::sewf
::sell::seww
::Senate::senate
::senator::senatow
::send::send
::senior::seniow
::sense::sense
::sensitive::sensitive
::sentence::sentence
::separate::sepawate
::sequence::sequence
::series::sewies
::serious::sewious
::seriously::sewiouswy
::serve::sewve
::service::sewvice
::session::session
::set::set
::setting::setting
::settle::settwe
::settlement::settwement
::seven::seven
::several::sevewaw
::severe::sevewe
::sex::sex
::sexual::sexuaw
::shade::shade
::shadow::shadow
::shake::shake
::shall::shaww
::shape::shape
::share::shawe
::sharp::shawp
::she::she
::sheet::sheet
::shelf::shewf
::shell::sheww
::shelter::shewtew
::shift::shift
::shine::shine
::ship::ship
::shirt::shiwt
::shit::shit
::shock::shock
::shoe::shoe
::shoot::shoot
::shooting::shooting
::shop::shop
::shopping::shopping
::shore::showe
::short::showt
::shortly::showtwy
::shot::shot
::should::shouwd
::shoulder::shouwdew
::shout::shout
::show::show
::shower::showew
::shrug::shwug
::shut::shut
::sick::sick
::side::side
::sigh::sigh
::sight::sight
::sign::sign
::signal::signaw
::significance::significance
::significant::significant
::significantly::significantwy
::silence::siwence
::silent::siwent
::silver::siwvew
::similar::simiwaw
::similarly::simiwawwy
::simple::simpwe
::simply::simpwy
::sin::sin
::since::since
::sing::sing
::singer::singew
::single::singwe
::sink::sink
::sir::siw
::sister::sistew
::sit::sit
::site::site
::situation::situation
::six::six
::size::size
::ski::ski
::skill::skiww
::skin::skin
::sky::sky
::slave::swave
::sleep::sweep
::slice::swice
::slide::swide
::slight::swight
::slightly::swightwy
::slip::swip
::slow::swow
::slowly::swowwy
::small::smaww
::smart::smawt
::smell::smeww
::smile::smiwe
::smoke::smoke
::smooth::smooth
::snap::snap
::snow::snow
::so::so
::so-called::so-cawwed
::soccer::soccew
::social::sociaw
::society::society
::soft::soft
::software::softwawe
::soil::soiw
::solar::sowaw
::soldier::sowdiew
::solid::sowid
::solution::sowution
::solve::sowve
::some::sowme
::somebody::somebody
::somehow::somehow
::someone::someone
::something::something
::sometimes::sometimes
::somewhat::somewhat
::somewhere::somewhewe
::son::son
::song::song
::soon::soon
::sophisticated::sophisticated
::sorry::sowwy
::sort::sowt
::soul::souw
::sound::sound
::soup::soup
::source::souwce
::south::south
::southern::southewn
::Soviet::soviet
::space::space
::Spanish::spanish
::speak::speak
::speaker::speakew
::special::speciaw
::specialist::speciawist
::species::species
::specific::specific
::specifically::specificawwy
::speech::speech
::speed::speed
::spend::spend
::spending::spending
::spin::spin
::spirit::spiwit
::spiritual::spiwituaw
::split::spwit
::spokesman::spokesman
::sport::spowt
::spot::spot
::spread::spwead
::spring::spwing
::square::squawe
::squeeze::squeeze
::stability::stabiwity
::stable::stabwe
::staff::staff
::stage::stage
::stair::staiw
::stake::stake
::stand::stand
::standard::standawd
::standing::standing
::star::staw
::stare::stawe
::start::stawt
::state::state
::statement::statement
::station::station
::statistics::statistics
::status::status
::stay::stay
::steady::steady
::steal::steaw
::steel::steew
::step::step
::stick::stick
::still::stiww
::stir::stiw
::stock::stock
::stomach::stomach
::stone::stone
::stop::stowp
::storage::stowage
::store::stowe
::storm::stowm
::story::stowy
::straight::stwaight
::strange::stwange
::stranger::stwangew
::strategic::stwategic
::strategy::stwategy
::stream::stweam
::street::stweet
::strength::stwength
::strengthen::stwengthen
::stress::stwess
::stretch::stwetch
::strike::stwike
::string::stwing
::strip::stwip
::stroke::stwoke
::strong::stwong
::strongly::stwongwy
::structure::stwuctuwe
::struggle::stwuggwe
::student::student
::studio::studio
::study::study
::stuff::stuff
::stupid::stupid
::style::stywe
::subject::subject
::submit::submit
::subsequent::subsequent
::substance::substance
::substantial::substantiaw
::succeed::succeed
::success::success
::successful::successfuw
::successfully::successfuwwy
::such::such
::sudden::sudden
::suddenly::suddenwy
::sue::sue
::suffer::suffew
::sufficient::sufficient
::sugar::sugaw
::suggest::suggest
::suggestion::suggestion
::suicide::suicide
::suit::suit
::summer::summew
::summit::summit
::sun::sun
::super::supew
::supply::suppwy
::support::suppowt
::supporter::suppowtew
::suppose::suppose
::supposed::supposed
::Supreme::supweme
::sure::suwe
::surely::suwewy
::surface::suwface
::surgery::suwgewy
::surprise::suwpwise
::surprised::suwpwised
::surprising::suwpwising
::surprisingly::suwpwisingwy
::surround::suwwound
::survey::suwvey
::survival::suwvivaw
::survive::suwvive
::survivor::suwvivow
::suspect::suspect
::sustain::sustain
::swear::sweaw
::sweep::sweep
::sweet::sweet
::swim::swim
::swing::swing
::switch::switch
::symbol::symbow
::symptom::symptom
::system::system
::table::tabwe
::tablespoon::tabwespoon
::tactic::tactic
::tail::taiw
::take::take
::tale::tawe
::talent::tawent
::talk::tawk
::tall::taww
::tank::tawnk
::tap::tap
::tape::tape
::target::tawget
::task::task
::taste::taste
::tax::tax
::taxpayer::taxpayew
::tea::tea
::teach::teach
::teacher::teachew
::teaching::teaching
::team::team
::tear::teaw
::teaspoon::teaspoon
::technical::technicaw
::technique::technique
::technology::technowogy
::teen::teen
::teenager::teenagew
::telephone::tewephone
::telescope::tewescope
::television::tewevision
::tell::teww
::temperature::tempewatuwe
::temporary::tempowawy
::ten::ten
::tend::tend
::tendency::tendency
::tennis::tennis
::tension::tension
::tent::tent
::term::tewm
::terms::tewms
::terrible::tewwibwe
::territory::tewwitowy
::terror::tewwow
::terrorism::tewwowism
::terrorist::tewwowist
::test::test
::testify::testify
::testimony::testimony
::testing::testing
::text::text
::than::than
::thank::thank
::thanks::thanks
::that::thawt
::the::the
::theater::theatew
::their::theiw
::them::thewm
::theme::theme
::themselves::themsewves
::then::then
::theory::theowy
::therapy::thewapy
::there::thewe
::therefore::thewefowe
::these::these
::they::they
::thick::thick
::thin::thin
::thing::thing
::think::think
::thinking::thinking
::third::thiwd
::thirty::thiwty
::this::thiws
::those::those
::though::though
::thought::thought
::thousand::thousand
::threat::thweat
::threaten::thweaten
::three::thwee
::throat::thwoat
::through::thwough
::throughout::thwoughout
::throw::thwow
::thus::thus
::ticket::ticket
::tie::tie
::tight::tight
::time::time
::tiny::tiny
::tip::tip
::tire::tiwe
::tired::tiwed
::tissue::tissue
::title::titwe
::to::tuwu
::tobacco::tobacco
::today::today
::toe::toe
::together::togethew
::tomato::tomato
::tomorrow::tomowwow
::tone::tone
::tongue::tongue
::tonight::tonight
::too::too
::tool::toow
::tooth::tooth
::top::top
::topic::topic
::toss::toss
::total::totaw
::totally::totawwy
::touch::touch
::tough::tough
::tour::touw
::tourist::touwist
::tournament::touwnament
::toward::towawd
::towards::towawds
::tower::towew
::town::town
::toy::toy
::trace::twace
::track::twack
::trade::twade
::tradition::twadition
::traditional::twaditionaw
::traffic::twaffic
::tragedy::twagedy
::trail::twaiw
::train::twain
::training::twaining
::transfer::twansfew
::transform::twansfowm
::transformation::twansfowmation
::transition::twansition
::translate::twanswate
::transportation::twanspowtation
::travel::twavew
::treat::tweat
::treatment::tweatment
::treaty::tweaty
::tree::twee
::tremendous::twemendous
::trend::twend
::trial::twiaw
::tribe::twibe
::trick::twick
::trip::twip
::troop::twoop
::trouble::twoubwe
::truck::twuck
::TRUE::twue
::truly::twuwy
::trust::twust
::truth::twuth
::try::twy
::trying::twying
::tube::tube
::tunnel::tunnew
::turn::tuwn
::TV::tv
::twelve::twewve
::twenty::twenty
::twice::twice
::twin::twin
::two::two
::type::type
::typical::typicaw
::typically::typicawwy
::ugly::ugwy
::ultimate::uwtimate
::ultimately::uwtimatewy
::unable::unabwe
::uncle::uncwe
::under::undew
::undergo::undewgo
::understand::undewstand
::understanding::undewstanding
::unfortunately::unfowtunatewy
::unfortunate::unfowtunate
::uniform::unifowm
::union::union
::unique::unique
::unit::unit
::United::united
::universal::univewsaw
::universe::univewse
::university::univewsity
::unknown::unknown
::unless::unwess
::unlike::unwike
::unlikely::unwikewy
::until::untiw
::unusual::unusuaw
::up::up
::upon::upon
::upper::uppew
::urban::uwban
::urge::uwge
::us::us
::use::use
::used::used
::useful::usefuw
::user::usew
::usual::usuaw
::usually::usuawwy
::utility::utiwity
::vacation::vacation
::valley::vawwey
::valuable::vawuabwe
::value::vawue
::variable::vawiabwe
::variation::vawiation
::variety::vawiety
::various::vawious
::vary::vawy
::vast::vast
::vegetable::vegetabwe
::vehicle::vehicwe
::venture::ventuwe
::version::vewsion
::versus::vewsus
::very::vewy
::vessel::vessew
::veteran::vetewan
::via::via
::vibe::vwibe
::victim::victim
::victory::victowy
::video::video
::view::view
::viewer::viewew
::village::viwwage
::violate::viowate
::violation::viowation
::violence::viowence
::violent::viowent
::virtually::viwtuawwy
::virtue::viwtue
::virus::viwus
::visible::visibwe
::vision::vision
::visit::visit
::visitor::visitow
::visual::visuaw
::vital::vitaw
::voice::voice
::volume::vowume
::volunteer::vowunteew
::vote::vote
::voter::votew
::vs::vs
::vulnerable::vuwnewabwe
::wage::wage
::wait::wait
::wake::wake
::walk::wawk
::wall::waww
::wander::wandew
::want::wawnt
::war::waw
::warm::wawm
::warn::wawn
::warning::wawning
::wash::wash
::waste::waste
::watch::watch
::water::watew
::wave::wave
::way::way
::we::we
::weak::weak
::wealth::weawth
::wealthy::weawthy
::weapon::weapon
::wear::weaw
::weather::weathew
::wedding::wedding
::week::week
::weekend::weekend
::weekly::weekwy
::weigh::weigh
::weight::weight
::welcome::wewcome
::welfare::wewfawe
::well::weww
::west::west
::western::westewn
::wet::wet
::whatever::watevew
::wheel::wheew
::when::whewn
::whenever::whenevew
::where::whewe
::whereas::wheweas
::whether::whethew
::which::which
::while::whiwe
::whisper::whispew
::white::white
::who::who
::whole::whowe
::whom::whom
::whose::whose
::why::why
::wide::wide
::widely::widewy
::widespread::widespwead
::wife::wife
::wild::wiwd
::will::wiww
::willing::wiwwing
::win::win
::wind::wind
::window::window
::wine::wine
::wing::wing
::winner::winnew
::winter::wintew
::wipe::wipe
::wire::wiwe
::wisdom::wisdom
::wise::wise
::wish::wish
::with::with
::withdraw::withdwaw
::within::within
::without::without
::witness::witness
::woman::woman
::wonder::wondew
::wonderful::wondewfuw
::wood::wood
::wooden::wooden
::word::wowd
::work::wowk
::worker::wowkew
::working::wowking
::works::wowks
::workshop::wowkshop
::world::wowwd
::worried::wowwied
::worry::wowwy
::worth::wowth
::would::wouwd
::wound::wound
::wrap::wwap
::write::wwite
::writer::wwitew
::writing::wwiting
::wrong::wwong
::yard::yawd
::yeah::yeah
::year::yeaw
::yell::yeww
::yellow::yewwow
::yes::yes
::yesterday::yestewday
::yet::yet
::yield::yiewd
::you::uw
::young::young
::your::youw
::yours::youws
::yourself::youwsewf
::youth::youth
::zone::zone

;slang/other words 

::hey::henwo
::dog::doggo
::cat::kitteh
::love::wuv
::fuck::fwick
::what::wat

::gg::
ends := ["gg <3", "gg :3"]
Random, num, 1, ends.Length()
sendData := ends[num]
SendInput %sendData%
return

::gr::
ends := ["gr <3", "gr :3"]
Random, num, 1, ends.Length()
sendData := ends[num]
SendInput %sendData%
return
